name: CI (golang)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Create dummy dist folder and file so go:embed doesn't fail
      - name: Create Dummy Frontend Dist
        run: |
          mkdir -p dist
          touch dist/index.html

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest